//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoilerMVC.Data
{
    using System;
    using System.Data.Entity;
    using BoilerMVC.Common;
    
    public partial class BoilerMVCEntities : DbContext, IUnitOfWork
    {
        public BoilerMVCEntities()
            : base("name=BoilerMVCEntities")
        {
        }
    
    	public void Commit()
    	{
    		this.SaveChanges();
    	}
    
        public DbSet<InRole> InRoles { get; set; }
        public DbSet<PasswordResetRequest> PasswordResetRequests { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
